### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by paul-bd** [pjmark/NIPET#3]
Hi, 

I am trying to install with pip your package on a Ubuntu 16.04 with Cuda 9.1 and cmake 3.5 in a conda environment with python 2.7 but installation fails. It seems that the dicom2niix is a badzip file. Any idea why because the links (https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20180622/dcm2niix_27-Jun-2018_lnx.zip) seems to be working? 

```
  ---------------------------------------------
    i> setting up NiftyPET tools ...
    i> conda environment found: niftypet
    ---------------------------------------------
    i> installing dcm2niix:
    >>>>> DISPLAY :0
    =================================================
    i> dcm2niix will be installed directly from:
       https://github.com/rordenlab/dcm2niix/releases
    =================================================
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-KlaYDt/nimpa/setup.py", line 70, in <module>
        Cnt = tls.install_tool('dcm2niix', Cnt)
      File "install_tools.py", line 219, in install_tool
        Cnt = download_dcm2niix(Cnt, path)
      File "install_tools.py", line 167, in download_dcm2niix
        zipf = zipfile.ZipFile(os.path.join(path, 'dcm2niix.zip'), 'r')
      File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/zipfile.py", line 770, in __init__
        self._RealGetContents()
      File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/zipfile.py", line 811, in _RealGetContents
        raise BadZipfile, "File is not a zip file"
    zipfile.BadZipfile: File is not a zip file
Cleaning up...
  Removing source in /tmp/pip-install-KlaYDt/nimpa
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-KlaYDt/nimpa/
Exception information:
Traceback (most recent call last):
  File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 324, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 154, in prep_for_dist
    self.req.run_egg_info()
  File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 486, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/hmn-mednuc/.conda/envs/niftypet/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-KlaYDt/nimpa/
```

Thanks for your help
Best regards
Paul

**Comment by pjmark** [comment]
Hello Paul


Thanks for trying NiftyPET.


That's really strange.  Do you have installed Anaconda 2 for Python?  That usually works straight out-of-box and it should handle well zip files.  Or there is a problem with a download.


It's also possible to make it through a manual install of the third party software (dcm2niix).  If so, I'm happy to help.  But it should work automatically.


Please let me know how it goes.  It does not sound like a serious problem, just one of the dependencies...


Best wishes,

Pawel

________________________________

**Comment by paul-bd** [comment]
Hi, thanks for your answer. I indeed have anaconda 3. 
I'll first start to install dicom2niix, as I would prefer to keep my allready install environment! I'll let you know if anything worked. 
Best regards
Paul

**Comment by paul-bd** [comment]
Hi again,
so the same problem happened even after building from source dicom2niix (via their github and the cmake function). It didn't neither worked after uninstalling anaconda3 and reinstalling anaconda2 with python 2.7.15 and the pip install. 
Any idea why or how to skip installation for dicom2niix.
Thanks for your help. 
Best regards

**Comment by pjmark** [comment]
Try to install dcm2niix totally independently, i.e., do the following:

  1.  Create folder ~/NiftyPET_tools/dcm2niix, if it does not exists
  2.  Within the folder clone the source into _src, i.e.: git clone https://github.com/rordenlab/dcm2niix _src
  3.  Go inside _src and then check out version 1.0.20180622, which is used in NiftyPET, i.e.: git checkout 4b641113273d86ad73123816993092fc643ac62f
  4.  Step out of _src and create build folder _bld and then step inside _bld
  5.  From within _bld run: ccmake ../_src
  6.  Run configure [c] and then choose BUILD_ALL_DEP=ON and change installation path to ~/NiftyPET_tools/dcm2niix, then configure [c] and generate [g]
  7.  Then run: make -j4, after which run: make install
  8.  Check if it works, ~/NiftyPET_tools/dcm2niix/bin/dcm2niix –version (it should show version v1.0.20180622)

If this does not work, it means there is a system problem which prohibits installing dcm2niix and has to be investigated from the third party perspective.

If it works, it should be then recognized automatically by NiftyPET as the correct/supported version.  Otherwise, it will try to reinstall it.

Let me know how it goes.

Best,
Pawel

**Comment by paul-bd** [comment]
Hi,

Thanks for this detailed response. 
Installation of dicom2niix following your steps perfectly worked and I now have installed dcm2niix v 1.0.20180622 successfully.

`(niftypet) hmn-mednuc@hmn-mednuc:~/NiftyPET_tools/dcm2niix/_bld$ ~/NiftyPET_tools/dcm2niix/bin/dcm2niix
Compression will be faster with 'pigz' installed
Chris Rorden's dcm2niiX version v1.0.20180622 GCC5.4.0 (64-bit Linux)
usage: dcm2niix [options] <in_folder>
`
Nevertheless it doensn't seem to be recognized as the error while installing niftypet still appears. 
I have added a log file for the complete installation process of this error. I think it doesn't recognize dcm2niix and still try to install it. Should it be added to the system path? 

Best regards,

Paul

[.log](https://github.com/pjmark/NiftyPET/files/2547365/default.log)
